/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package packageTest;

public class Library {
	static String awnser = "Hello from Package!";

	public boolean someLibraryMethod() {
		return true;
	}

	public String libTestFunction() {
		return awnser;
	}
}
